name: Android CI

on: push

jobs:
  test:
    name: Run Instrumented Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create AVD
        run: echo "no" | avdmanager create avd --force --name Pixel_3a_API_30 --abi google_apis/x86 --package 'system-images;android-30;google_apis;x86' --device "pixel_3a"

      - name: Start emulator
        run: |
          echo "Starting emulator"
          nohup $ANDROID_HOME/emulator/emulator -avd Pixel_3a_API_30 -no-snapshot > /dev/null 2>&1 &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: Run instrumented tests
        run: ./gradlew connectedDebugAndroidTest